version: '3.1'

services:
  api:
    build: ./
    image: node
    container_name: beer_lovers_api
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
      - "../slike:/usr/src/slike"
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local